/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homework_mystere;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author fcmam5
 */
public class Second extends javax.swing.JFrame {
    
int levelRange = 10;
int number = 1+ (int)(Math.random()*levelRange);
int mo7awala; 
int life;
int rounds;
int level = 1;

//LEVEL 3
/**
 * Level3: 
 * You need to pass the level2
 * And the range is [1-500]
 */
    void thirdLevel3(){
            if((jTextField1.isEnabled())&&(level>2)){
                JOptionPane.showConfirmDialog(this, "Oh brave, Good luck! \nYou'll need it","Level 3",JOptionPane.DEFAULT_OPTION);
            //Reset game initial values
            levelRange = 500;
            number = 1+ (int)(Math.random()*levelRange);
            this.mo7awala = 1;
            life = 1;
            this.rounds= 1;
            //Set text to default
            jLabel1.setText("Hey lucky! Now guess a number between 1 and 500");
            jTextField1.setText(null);
            //Get hearts back ^_^
            life1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart.png"))); 
            life2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart.png")));
            life3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart.png")));
            }
            else
                JOptionPane.showConfirmDialog(this, "Not today superman, try again!","Bad luck!",JOptionPane.DEFAULT_OPTION);
        }
    
    /**
     * Level 2
     * The range is [1-100]
     * You can play if you didn't failed in the 1st level (Text field isn't disabled)
     */
    void secondLevel2(){
            if((jTextField1.isEnabled())&&(level>1)){
            //Reset game initial values
            levelRange = 100;
            number = 1+ (int)(Math.random()*levelRange);
            this.mo7awala = 1;
            life = 1;
            this.rounds= 1;
            //Set text to default
            jLabel1.setText("Level 2, Guess between 1 and 100");
            jTextField1.setText(null);
            //Get hearts back ^_^
            life1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart.png"))); 
            life2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart.png")));
            life3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart.png")));
            }
            else
              JOptionPane.showConfirmDialog(this, "That's cute Mr cheater, please Reset & play again","Trying to pass",JOptionPane.DEFAULT_OPTION);

    }
    
    /**
     * Level1
     */
    void firstlevel1(){
           //Reset game initial values
        levelRange = 10;
        number = 1+ (int)(Math.random()*levelRange);
        this.mo7awala = 1;
        life = 1;
        this.rounds= 1;
        //Set text to default
        jLabel1.setText("Good luck !");
        jTextField1.setEditable(true);
        jTextField1.setText(null);
        //Get hearts back ^_^
        life1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart.png"))); // NOI18N
        life2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart.png"))); // NOI18N
        life3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart.png")));
        
    }
//************************************************************************************
    /**
     * Creates new form Second
     */
    public Second() {
        
        initComponents();
        this.mo7awala = 1;
        life = 1;
        this.rounds= 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        life1 = new javax.swing.JLabel();
        life2 = new javax.swing.JLabel();
        life3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        jTextField1.setBackground(new java.awt.Color(255, 255, 153));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("Good luck !");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Good luck !");

        life1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart.png"))); // NOI18N

        life2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart.png"))); // NOI18N

        life3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart.png"))); // NOI18N

        jLabel3.setText("Life");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(life1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(life2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(life3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(life1)
                    .addComponent(life3)
                    .addComponent(life2)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/po.gif"))); // NOI18N

        jMenu1.setText("Game");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New game");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu2.setText("Change level");

        jMenuItem3.setText("Level 1");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Level 2");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Level 3");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        try{
        if(rounds<=3)
        {
            if ((number == Integer.parseInt(jTextField1.getText()))&& mo7awala<=7){
                
                level++;
                switch(level){
                    case 2: 
                        new Win().setVisible(true);
                        secondLevel2();
                        break;
                        
                    case 3: 
                        thirdLevel3();
                        break;
                    case 4: JOptionPane.showConfirmDialog(this, "Hello superLucky! \nPlease send me a screenshot at\nFacebook.com/Fcmam5.me","Super lucky !",JOptionPane.DEFAULT_OPTION);break;
                }
                
        }
            else{
                 if(mo7awala<=7){
                     //Less than 7 tries
                     if(number < Integer.parseInt(jTextField1.getText()))
                        jLabel1.setText("Less.. ");
                     else
                        jLabel1.setText("More !"); 
                mo7awala++;
                jTextField1.selectAll();
                 }
                 
                 else
                 {
                     jLabel1.setText("On no, Try again !");
                     mo7awala = 1;
                     jTextField1.setText("");
                     
                     switch(rounds){
                         case 1: life3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart_g.png")));
                         
                             break;
                         case 2: life2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart_g.png")));
                             break;
                         case 3: life1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heart_g.png")));
                             break;
                     }
                     rounds++;
                 }
            }
        }
         else{
                    jTextField1.setEnabled(false);
                    jLabel1.setText("Uh! Good luck next time, You'll need it");
                    JOptionPane.showConfirmDialog(this, "The mysterious number was: "+number,"Almost there :(",JOptionPane.DEFAULT_OPTION);

                 }
            }
            catch(NumberFormatException eNumber){
               JOptionPane.showMessageDialog(this, "Error my friend! Check why:\n"+eNumber,"Error !",JOptionPane.ERROR_MESSAGE);

            }
  
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.selectAll();
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
           firstlevel1();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
                   firstlevel1();
            }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        secondLevel2();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       //LEVEL3
        thirdLevel3();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Second.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Second().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel life1;
    private javax.swing.JLabel life2;
    private javax.swing.JLabel life3;
    // End of variables declaration//GEN-END:variables
}
